### PR TITLE
Coding Resource for beginners

### PR DESCRIPTION
**Pull request by g-akash**
Added a resource for coding with detailed tutorials and practice tests along with prizes. Its free for all.

### CODE REVIEW

**Comment by dreamtocode** [comment]
Hi g-akash, thanks for PR.
I think that it does not apply to our repository's formatting style. It means that you need to add space after +(plus sign)
I hope it helps.

**Comment by g-akash** [comment]
Hi! Its still having checks failed. Can you please check it.

**Comment by dreamtocode** [comment]
Sure.
Congrats you almost got it !
Visually it's correct but not syntactically because two plus sign is not correct style, all you need is one. Just remove second one. 
Ex: 
+ <a href="https://codecombat.com/" target="_blank"> CodeCombat </a> An online game that teaches programming. Students write code in real programming languages (Python, JavaScript, Lua, CofeeScript, Clojure). :arrows_counterclockwise:
It starts with one + (not two) and that's where your mistake lies. Does it make sense ? 
Second thing that you can do is copy this example and change link, header, and description appropriately.
Hope it helps, I'll check it tomorrow again.

**Comment by g-akash** [comment]
hi, I did as you said but few checks have still failed. secondly I think the other plus sign that you are talking about is because of patching. I used only one plus sign. And I used the same method of copying the last resource and making the desired changes. The second plus sign says that this resource has been added. You would also have seen a minus sign in last commit showing that the earlier has been removed. Let me know if I am wrong here.

**Comment by g-akash** [comment]
please preview whole file with the last commit. it looks fine over here "https://github.com/g-akash/awesome-resources/blob/a20882a85469bacf8c7ccb371e3cb1c42ce3bf39/README.md"

**Comment by dreamtocode** [comment]
You are right. Thanks

**Pull request merged**
