### PR TITLE
Added Watch and Code

### PR DESCRIPTION
**Pull request by zanderlx**

### CODE REVIEW

**Comment by dreamtocode** [comment]
Hi @zanderlx 

Thanks for sending pr I appreciate it. Please add it at the end of Sololearn and if everything will be ok I'll merge. Hope it helps.

Have a great day!

**Comment by zanderlx** [comment]
Updated "Watch and Code" by adding it to the end of the list. Hope everything is correct.

**Comment by dreamtocode** [comment]
Hi @zanderlx 

Thanks again. Glad to see that everything is correct.  

Have a super day!

**Comment by dreamtocode** [comment]
Hi @zanderlx

Thanks again. Glad to see that everything is correct.

Have a super day!

**Comment by dreamtocode** [comment]
Hi @zanderlx

Thanks again. I see that repository that submitted this pull request has been deleted so I will add this resource for you.

Have a super day!

**Pull request closed without merging**
